// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRbgx1QzMohdCsnUgl-umGpt1IjTyk21M',
    appId: '1:1088975160587:web:dab1b8ef463cc10a86ce0e',
    messagingSenderId: '1088975160587',
    projectId: 'b2b-saas-defa2',
    authDomain: 'b2b-saas-defa2.firebaseapp.com',
    storageBucket: 'b2b-saas-defa2.firebasestorage.app',
    measurementId: 'G-RNPMR9Z4TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQIUrg7XqTnOFNNhz9LnNBYq8wcb8GMk',
    appId: '1:1088975160587:android:8ba8e5a4252beb7b86ce0e',
    messagingSenderId: '1088975160587',
    projectId: 'b2b-saas-defa2',
    storageBucket: 'b2b-saas-defa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATpjNnSwt7rVUw6QKGJ5qX9DqmwVJPZj0',
    appId: '1:1088975160587:ios:b30434879c7b929086ce0e',
    messagingSenderId: '1088975160587',
    projectId: 'b2b-saas-defa2',
    storageBucket: 'b2b-saas-defa2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpjNnSwt7rVUw6QKGJ5qX9DqmwVJPZj0',
    appId: '1:1088975160587:ios:b30434879c7b929086ce0e',
    messagingSenderId: '1088975160587',
    projectId: 'b2b-saas-defa2',
    storageBucket: 'b2b-saas-defa2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRbgx1QzMohdCsnUgl-umGpt1IjTyk21M',
    appId: '1:1088975160587:web:ed2e1b5515679f4786ce0e',
    messagingSenderId: '1088975160587',
    projectId: 'b2b-saas-defa2',
    authDomain: 'b2b-saas-defa2.firebaseapp.com',
    storageBucket: 'b2b-saas-defa2.firebasestorage.app',
    measurementId: 'G-YEHK1MG374',
  );
}